#!/bin/bash

if dmesg | grep "usb 5-1: pl2303 converter now attached to ttyUSB1" ; then
 portti=/dev/ttyUSB1
else
 portti=/dev/ttyUSB0
fi

/bin/stty -F $portti 4800

str=$1
len=${#str}
c=0
while [ $c -lt $len ] ; do
 char=${str:$c:1} 
 char=$( echo "$char" | /bin/sed -s y/abcdefghijklmnopqrstuvxyäöÄÖ°/ABCDEFGHIJKLMNOPQRSTUVXYababc/ )
 echo -n "$char" > $portti
# if [ "$char" == "." ] ; then sleep 0.01 ; else sleep 0.011 ; fi
 c=$(( $c + 1 ))
done
